### ISSUE TITLE
Maybe refactor..?

### ISSUE THREAD

**Issue by shift-d** [deadblackclover/clover#6]
Hello! I found this emacs config on dev.to, checked out and it looks pretty cool! The only thing that i didn't like for now - how you've organized .el files. Since you have more than 5, you could try making subdirectories inside ./lisp. Like for lang settings, etc.

Good luck!

**Comment by deadblackclover** [comment]
This is a very good observation. I will try to fix it soon.

**Comment by deadblackclover** [comment]
Slightly corrected the file structure. I think you can close the issue
